export const GAMING_KEYWORDS = [
  "game", "games", "gaming", "gamer", "gamers",
  "play-to-earn", "p2e", "p2w", "play2earn",
  "mmo", "mmorpg", "rpg", "roleplay", "role-playing",
  "metaverse", "virtual world",
  "craft", "crafting",
  "runner", "racing",
  "battle", "battler", "arena",
  "quest", "dungeon", "raid", "roguelike",
  "strategy", "tactics",
  "simulator", "simulation",
  "shooter", "fps", "action",
  "card game", "trading card",
  "mobil game", "mobile gaming",
  "idle game", "idle rpg",
] as const;
